---
- name: set ipv4 routing
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: ensure that the kubelet is running
  service:
    name: kubelet
    state: started
    enabled: true

# Required by the docker_image ansible module
- name: install docker-py
  pip:
    name: docker-py
  when: kubernetes_enable_cached_images|bool and kubernetes_cached_images|length > 0

- name: cache docker images for kubeadm
  docker_image:
    name: "{{ item }}"
  with_items: kubernetes_cached_images
  when: kubernetes_enable_cached_images|bool and kubernetes_cached_images|length > 0

- name: set kubernetes version file
  template:
    dest: /etc/kubernetes_community_ami_version
    src: etc/kubernetes_community_ami_version
